spring:
  datasource:
    url: jdbc:mysql://localhost:3306/DB-master?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

